version: '3.8'
volumes:
  php-fpm-socket:
  db-store:
services:
  # https-portal:
  #   image: steveltn/https-portal:1
  #   ports:
  #     - 82:81
  #     - 443:443
  #   links:
  #     - api-server
  #   restart: always
  #   environment:
  #     STAGE: local
  #     DOMAINS: 'dev.api.upsw.cc -> http://api-server'
  #   volumes:
  #     - ./infra/ssl-certs:/var/lib/https-portal

  # upsw
  api-server:
    build:
      context: .
      dockerfile: ./infra/api.upsw/Dockerfile
    privileged: true
    ports:
      - 8000:80
    restart: always
    depends_on:
      - db-server
    links:
      - db-server
    volumes:
      - .:/var/www/html:cached
  # MySQL
  db-server:
    image: mysql:8.0.20
    environment:
      MYSQL_ROOT_PASSWORD: kN4RtHzS
      MYSQL_DATABASE: upsw
      MYSQL_USER: upsw
      MYSQL_PASSWORD: 5T6V3VN9QJ
    volumes:
      - db-store:/var/lib/mysql
    ports:
    - 3307:3306
    tty: true
    restart: always

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
    - PMA_ARBITRARY=1
    - PMA_HOSTS=db-server
    - PMA_USER=upsw
    - PMA_PASSWORD=5T6V3VN9QJ
    ports:
    - 8082:80
